version: '3.8'
services:
  db:
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: user_service
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    # environment:
    #   DATABASE_URL: "postgresql://postgres:secret123@db:5432/user_service?schema=public"
    #   JWT_SECRET: "your_jwt_secret_here"
    ports:
      - "3000:3000"
    # Запускаем миграции, сид и старт приложения
    command: sh -c "npm run prisma:migrate && npm run seed:prod && npm run start"

volumes:
  db-data:
